apiVersion: v1
kind: Service
metadata:
  name: charon-blog-service
  namespace: default
  labels:
    app: charon-blog
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: charon-blog